version: '3'

services:
  dbwr:
    build:
      context: config 
    image: 'dbwr'
    container_name: dbwr
    network_mode: 'host'
      #ports:
      #- '8088:8080'
    volumes:
      - './bob:/bob'
        #- './config/setenv.sh:/opt/tomcat/bin/setenv.sh'
    environment:
      EPICS_CA_ADDR_LIST: ""
      PV_WRITE_SUPPORT: "false"
      DBWR1: "/bob/test.bob"
