version: '3'

services:
  dbwr:
    build:
      context: config 
    image: 'dbwr'
    container_name: dbwr
    network_mode: 'host'
      #ports:
      #- '8088:8080'
    volumes:
      - './bob:/bob'
    environment:
      EPICS_CA_ADDR_LIST: "10.0.0.10"
      EPICS_CA_MAX_ARRAY_BYTES:
      PV_THROTTLE_MS: 1000
      PV_ARRAY_THROTTLE_MS: 10000
      PV_WRITE_SUPPORT: "false"
      DBWR1: "/bob/test.bob"
